on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install hexo-cli
        run: npm install hexo-cli --no-bin-links

      - name: Install dependencies
        run: npm install

      - name: Debug ls themes folder
        run: ls -lR themes/
      - name: Check hexo-cli installation
        run: npm list -g --depth=0
        
      - name: Generate static files
        run: npx hexo clean && npx hexo generate
      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



